name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: |
          yarn install
      - name: typecheck
        run: |
          yarn run typecheck
      - name: Test
        run: |
          yarn run spec
      - name: Compile main
        run: |
          yarn run pack:main
      - name: Compile renderer
        run: |
          yarn run pack:renderer
